version: "3.7"

services:
  app:
    build: ./app-shell
    ports:
      - 8000:80
    networks:
      - app-net

  micro-frontend-tech-list:
    build: ./micro-frontends/tech-list
    ports:
      - 8001:80
    networks:
      - app-net

  micro-frontend-tech-card:
    build: ./micro-frontends/tech-card
    ports:
      - 8002:80
    networks:
      - app-net

  api:
    build: ./api
    image: app
    ports:
      - 8003:80
    networks:
      - app-net

networks:
  app-net:
