version: "3.7"

services:
  app-shell:
    build: ./app-shell
    image: app-shell
    ports:
      - 8000:80

  mf-browse:
    build: ./mf-browse
    image: mf-browse
    ports:
      - 8001:80

  mf-detail:
    build: ./mf-detail
    image: mf-detail
    ports:
      - 8002:80

  api:
    build: ./api
    image: api
    ports:
      - 8003:80
