version: "3.7"

services:
  micro-frontends-app-shell:
    build: ./app-shell
    image: micro-frontends-app-shell
    ports:
      - 8000:80
    networks:
      - app-net

  micro-frontends-tech-list:
    build: ./micro-frontends/tech-list
    image: micro-frontends-tech-list
    ports:
      - 8001:80
    networks:
      - app-net

  micro-frontends-tech-card:
    build: ./micro-frontends/tech-card
    image: micro-frontends-tech-card
    ports:
      - 8002:80
    networks:
      - app-net

  micro-frontends-api:
    build: ./api
    image: micro-frontends-api
    ports:
      - 8003:80
    networks:
      - app-net

networks:
  app-net:
