version: "3.9"

services:
  proxy:
    build: ./proxy
    image: proxy
    ports:
      - 8000:80
    networks:
      - micro-frontends-app

  app-shell:
    build: ./app-shell
    image: app-shell
    networks:
      - micro-frontends-app

  mf-browse:
    build: ./mf-browse
    image: mf-browse
    networks:
      - micro-frontends-app

  mf-detail:
    build: ./mf-detail
    image: mf-detail
    networks:
      - micro-frontends-app

  api:
    build: ./api
    image: api
    networks:
      - micro-frontends-app

networks:
  micro-frontends-app:
    name: micro-frontends-app
