const {
  VITE_MF_BROWSE_URL: MF_BROWSE_URL,
  VITE_MF_BROWSE_ID: MF_BROWSE_ID,
  VITE_MF_DETAIL_URL: MF_DETAIL_URL,
  VITE_MF_DETAIL_ID: MF_DETAIL_ID,
} = import.meta.env;

export { MF_BROWSE_URL, MF_BROWSE_ID, MF_DETAIL_URL, MF_DETAIL_ID };
